CREATE DATABASE QUANLYCAFE

CREATE TABLE TABLECAFE
(
	ID INT IDENTITY PRIMARY KEY,		  
	NAME NVARCHAR(50) NOT NULL,			
	STATUS NVARCHAR(50)	NOT NULL		
)

CREATE TABLE ACCOUNT
(		
	LOGINNAME NVARCHAR(50) PRIMARY KEY, 
	DISPLAYNAME NVARCHAR(50) NOT NULL,		    
	PASS NVARCHAR(50) NOT NULL,	      
	TYPEACC INT NOT NULL			 
)

CREATE TABLE CATEGORY 
(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(50) NOT NULL
)

CREATE TABLE FOOD
(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(50) NOT NULL,
	IDCATEGORY INT NOT NULL,
	PRICE MONEY NOT NULL

	FOREIGN KEY(IDCATEGORY) REFERENCES DBO.CATEGORY(ID)
)

CREATE TABLE BILL
(
	ID INT IDENTITY PRIMARY KEY,
	DATECHECKIN DATETIME NOT NULL,
	DATECHECKOUT DATETIME,
	IDTABLE INT NOT NULL,
	STATUS INT NOT NULL

	FOREIGN KEY(IDTABLE) REFERENCES DBO.TABLECAFE(ID)
)

CREATE TABLE BILLDETAILS
(
	ID INT IDENTITY PRIMARY KEY,
	IDBILL INT NOT NULL,
	IDFOOD INT NOT NULL,
	AMOUNT INT NOT NULL,
	TOTALPRICE MONEY NOT NULL

	FOREIGN KEY(IDBILL) REFERENCES DBO.BILL(ID),
	FOREIGN KEY(IDFOOD) REFERENCES DBO.FOOD(ID)

)